name: Pull Request Workflow
on:
  pull_request:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Clone script repository with SSH
        uses: actions/checkout@v2
        with:
          repository: thethiago27/ci-cd
          ref: main
          token: ${{ secrets.GIT_TOKEN }}
          path: ci-cd
      - name: Setup Environment
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          export PULL_REQUEST_NUMBER=$(echo "$GITHUB_EVENT_PATH" | jq -r '.pull_request.number')
          export GITHUB_REPOSITORY=$(echo "$GITHUB_EVENT_PATH" | jq -r '.pull_request.head.repo.full_name')
          export GITHUB_SHA=$(echo "$GITHUB_EVENT_PATH" | jq -r '.pull_request.head.sha')
          export GITHUB_REF=$(echo "$GITHUB_EVENT_PATH" | jq -r '.pull_request.head.ref')
      - name: Run script
        run: |
          echo "PULL_REQUEST_NUMBER: $PULL_REQUEST_NUMBER"
          cd ci-cd
          ./run.sh